apiVersion: batch/v1
kind: Job
metadata:
  name: insert-data
spec:
  template:
    spec:
      containers:
      - name: insert-data
        image: postgres-service:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "insert-data.py"]
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:12345@postgres-service.default.svc.cluster.local:5432/petstore"
      restartPolicy: Never
  backoffLimit: 4
