apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-ingress
  namespace: default
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - host: api.petstore.local
    http:
      paths:
        # Productos
        - path: /api/products
          pathType: Prefix
          backend:
            service:
              name: product-service
              port:
                number: 80
        - path: /api/products/{productId}
          pathType: Prefix
          backend:
            service:
              name: product-service
              port:
                number: 80
        - path: /api/products/{productId}/reviews
          pathType: Prefix
          backend:
            service:
              name: review-service
              port:
                number: 80
        - path: /api/products/{productId}/reviews/{reviewId}
          pathType: Prefix
          backend:
            service:
              name: review-service
              port:
                number: 80

        # Categorías
        - path: /api/categories
          pathType: Prefix
          backend:
            service:
              name: category-service
              port:
                number: 80
        - path: /api/categories/{categoryId}
          pathType: Prefix
          backend:
            service:
              name: category-service
              port:
                number: 80

        # Usuarios
        - path: /api/users/register
          pathType: Prefix
          backend:
            service:
              name: user-service
              port:
                number: 80
        - path: /api/users/login
          pathType: Prefix
          backend:
            service:
              name: user-service
              port:
                number: 80
        - path: /api/users/profile
          pathType: Prefix
          backend:
            service:
              name: user-service
              port:
                number: 80
        - path: /api/users/addresses
          pathType: Prefix
          backend:
            service:
              name: user-service
              port:
                number: 80
        - path: /api/users/addresses/{addressId}
          pathType: Prefix
          backend:
            service:
              name: user-service
              port:
                number: 80

        # Carrito de Compras
        - path: /api/cart
          pathType: Prefix
          backend:
            service:
              name: cart-service
              port:
                number: 80
        - path: /api/cart/items
          pathType: Prefix
          backend:
            service:
              name: cart-service
              port:
                number: 80
        - path: /api/cart/items/{itemId}
          pathType: Prefix
          backend:
            service:
              name: cart-service
              port:
                number: 80

        # Pedidos
        - path: /api/orders
          pathType: Prefix
          backend:
            service:
              name: order-service
              port:
                number: 80
        - path: /api/orders/{orderId}
          pathType: Prefix
          backend:
            service:
              name: order-service
              port:
                number: 80
        - path: /api/orders/{orderId}/cancel
          pathType: Prefix
          backend:
            service:
              name: order-service
              port:
                number: 80

        # Búsqueda
        - path: /api/search
          pathType: Prefix
          backend:
            service:
              name: search-service
              port:
                number: 80
